# Generated by Django 3.2 on 2022-05-19 20:47

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120, verbose_name='Категория')),
                ('slug_category', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, unique=True, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_now', models.FloatField(verbose_name='Цена в текущий момент')),
                ('price_old', models.FloatField(blank=True, null=True, verbose_name='Старая цена')),
                ('discounted_price', models.FloatField(verbose_name='Скидка')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошло модерацию')),
                ('guarantee', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Гарантия')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество товара')),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2040)], verbose_name='Год выпуска')),
                ('status', models.CharField(choices=[('Have', 'Есть в наличии'), ('Havent', 'Временно отсутвует')], default='Havent', max_length=120, verbose_name='Статус товара')),
                ('characteristics', models.JSONField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_product', to='product.category', verbose_name='Категория')),
                ('colors', models.ManyToManyField(blank=True, related_name='product_colors', to='product.ProductColor', verbose_name='Цвета')),
                ('photo', models.ManyToManyField(related_name='product_photos', to='product.ProductImage', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
