# Generated by Django 3.2 on 2022-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='product_colors', to='product.ProductColor', verbose_name='Цвета'),
        ),
    ]
