# Generated by Django 3.2 on 2022-05-24 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basket',
            field=models.ManyToManyField(blank=True, default=None, related_name='basket_products', to=settings.AUTH_USER_MODEL, verbose_name='Добавить в корзину'),
        ),
    ]
