# Generated by Django 3.2 on 2022-05-31 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_product_price_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite_product',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='favorite_news', to=settings.AUTH_USER_MODEL, verbose_name='Добавить в избранное'),
        ),
        migrations.CreateModel(
            name='FavoriteUserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_product_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь добавивший в избранное')),
                ('product_in_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт добаленный в избранное')),
            ],
            options={
                'verbose_name': 'Избранная новость',
                'verbose_name_plural': 'Избранные новости',
            },
        ),
    ]
