# Generated by Django 3.2 on 2022-05-31 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20220531_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite_product',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_news', to=settings.AUTH_USER_MODEL, verbose_name='Добавить в избранное'),
        ),
    ]
