# Generated by Django 3.2 on 2022-06-01 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_alter_product_favorite_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteuserproduct',
            options={'verbose_name': 'Favorites product', 'verbose_name_plural': 'Favorites products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite_product',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_products', to=settings.AUTH_USER_MODEL, verbose_name='Добавить в избранное'),
        ),
    ]
