# Generated by Django 3.2 on 2022-06-05 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220601_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2147483647)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_now',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в текущий момент'),
        ),
    ]
