# Generated by Django 3.2 on 2022-05-30 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('final_price_cart', models.IntegerField(default=0, verbose_name='Общая сумма всех товаров')),
                ('total_discount_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая сумма скидок')),
                ('total_not_discount_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая сумма цен без скидок')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)], verbose_name='Количество')),
                ('final_price', models.IntegerField(default=0, verbose_name='Общая сумма')),
                ('final_total_discount', models.IntegerField(default=0, verbose_name='Общая сумма скидок в корзине')),
                ('final_price_not_discount', models.IntegerField(default=0, verbose_name='Общая сумма цен без скидок в корзине')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='cart.cart', verbose_name='Корзина')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продукт для корзины',
                'verbose_name_plural': 'Продукты для корзины',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_in_cart', to='cart.CartProduct'),
        ),
    ]
