# Generated by Django 3.2 on 2022-06-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Product in cart', 'verbose_name_plural': 'Products in cart'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_discount_price',
            field=models.IntegerField(default=0, verbose_name='Общая сумма скидок'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_not_discount_price',
            field=models.IntegerField(default=0, verbose_name='Общая сумма цен без скидок'),
        ),
    ]
