# Generated by Django 3.2 on 2022-05-30 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_alter_cartproduct_count_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='final_price_not_discount',
            field=models.IntegerField(default=0, verbose_name='Общая сумма цен без скидок'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='final_total_discount',
            field=models.IntegerField(default=0, verbose_name='Общая сумма скидок'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_cart_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
