# Generated by Django 3.2 on 2022-05-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220530_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_discount_price',
            field=models.IntegerField(default=0, verbose_name='Общая сумма скидок'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_not_discount_price',
            field=models.IntegerField(default=0, verbose_name='Общая сумма цен без скидок'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price_not_discount',
            field=models.IntegerField(default=0, verbose_name='Общая сумма цен без скидок в корзине'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_total_discount',
            field=models.IntegerField(default=0, verbose_name='Общая сумма скидок в корзине'),
        ),
    ]
