# Generated by Django 3.2 on 2022-06-13 11:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, populate_from='username', verbose_name='URL'),
        ),
    ]
