# Generated by Django 3.2 on 2022-05-11 13:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='system_images/defult.jpg', null=True, upload_to='system_images', verbose_name='Аватарка пользователя'),
        ),
    ]
