# Generated by Django 3.2 on 2022-05-17 17:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='system_images/defult.jpg', null=True, upload_to='avatars', verbose_name='Аватарка пользователя'),
        ),
    ]
