# Generated by Django 3.2 on 2022-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=255, verbose_name='Основная роль пользователя'),
        ),
    ]
